"""
Configuration module for Nutrition Agentic AI
Loads settings from .env and defines constants
"""
import os
from dotenv import load_dotenv

load_dotenv()

# ── IBM watsonx.ai credentials ──────────────────────────────────────────────
IBM_API_KEY    = os.getenv("IBM_API_KEY", "")
IBM_PROJECT_ID = os.getenv("IBM_PROJECT_ID", "")
IBM_REGION     = os.getenv("IBM_REGION", "https://us-south.ml.cloud.ibm.com").strip()

# ── Model settings ───────────────────────────────────────────────────────────
MODEL_ID = "ibm/granite-4-h-small"       # IBM Granite 4 – available in all watsonx.ai tiers

GENERATE_PARAMS = {
    "decoding_method": "greedy",
    "max_new_tokens": 1500,
    "min_new_tokens": 200,
    "temperature": 0.7,
    "top_k": 50,
    "top_p": 0.95,
    "repetition_penalty": 1.1,
}

# ── Application constants ────────────────────────────────────────────────────
APP_NAME    = "NutritionAgent – IBM Granite AI"
APP_VERSION = "1.0.0"
APP_AUTHOR  = "IBM Bob Project"

DIET_OPTIONS       = ["Vegetarian", "Non-Vegetarian", "Vegan", "Pescatarian"]
MEDICAL_CONDITIONS = [
    "None",
    "Diabetes (Type 1)",
    "Diabetes (Type 2)",
    "Hypertension / High Blood Pressure",
    "High Cholesterol",
    "Heart Disease",
    "Kidney Disease",
    "Thyroid Disorder",
    "Celiac Disease / Gluten Intolerance",
    "Lactose Intolerance",
    "Other (specify)",
]

# ── Guardrail keywords (refuse or warn) ─────────────────────────────────────
HARMFUL_KEYWORDS = [
    "extreme fasting", "starvation diet", "crash diet", "500 calories",
    "anorexia", "bulimia", "self-harm", "suicide", "laxative abuse",
    "steroids", "illegal supplement",
]

# ── Medical disclaimer ───────────────────────────────────────────────────────
MEDICAL_DISCLAIMER = """
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚕  IMPORTANT MEDICAL DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This nutrition plan is generated by an AI system (IBM Granite LLM)
for INFORMATIONAL PURPOSES ONLY. It does NOT constitute medical
advice, diagnosis, or treatment.

• Always consult a qualified healthcare professional or registered
  dietitian before making significant changes to your diet,
  especially if you have an existing medical condition.
• Individual nutritional needs vary and may differ from the
  AI-generated recommendations.
• Emergency situations: call your local emergency number immediately.
• The developers and IBM are NOT liable for any health outcomes
  resulting from the use of this application.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
