"""
Nutrition plan generator module.
Orchestrates the LLM call and saves the result to a Markdown file.
"""
from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.spinner import Spinner
from rich.live import Live

from nutrition_agent.llm_client import NutritionLLMClient
from nutrition_agent.config import APP_NAME, APP_VERSION

console = Console()

OUTPUT_DIR = Path("nutrition_plans")


# ────────────────────────── helpers ─────────────────────────────────────────

def _safe_filename(name: str, city: str) -> str:
    """Build a filesystem-safe filename."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = re.sub(r"[^\w\-]", "_", name)
    safe_city = re.sub(r"[^\w\-]", "_", city)
    return f"nutrition_plan_{safe_name}_{safe_city}_{timestamp}.md"


def _build_md_document(profile: dict, plan_text: str) -> str:
    """Wrap the AI plan in a full Markdown document."""
    now = datetime.now().strftime("%A, %d %B %Y – %H:%M")
    conditions = ", ".join(profile.get("medical_history", ["None"]))

    header = f"""# 🥗 Personalised Nutrition Plan
**Generated by:** {APP_NAME} v{APP_VERSION}  
**Date:** {now}

---

## 👤 User Profile
| Field | Value |
|-------|-------|
| Name | {profile['name']} |
| Age | {profile['age']} years |
| Diet Preference | {profile['diet_preference']} |
| Medical History | {conditions} |
| Location | {profile['city']}, {profile['country']} |
| Health Goal | {profile.get('goal', 'General healthy eating')} |

---

"""
    return header + plan_text


def save_plan(profile: dict, plan_text: str) -> Path:
    """Save the nutrition plan to a Markdown file. Returns the file path."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    filename = _safe_filename(profile["name"], profile["city"])
    filepath = OUTPUT_DIR / filename

    document = _build_md_document(profile, plan_text)
    filepath.write_text(document, encoding="utf-8")
    return filepath


# ────────────────────────── main generator ──────────────────────────────────

def generate_and_display_plan(profile: dict) -> str:
    """
    Call IBM Granite, display the result, save to .md, return plan text.
    """
    console.print(
        "\n[bold green]🤖 Connecting to IBM Granite LLM…[/bold green]\n"
        "Generating your personalised nutrition plan. This may take 20–40 seconds."
    )

    client = NutritionLLMClient()

    # ── spinner while waiting for LLM ───────────────────────────────────────
    plan_text: str = ""
    with Live(
        Panel(Spinner("dots", text="Thinking…"), title="[bold cyan]IBM Granite AI[/bold cyan]"),
        refresh_per_second=10,
    ):
        plan_text = client.generate_nutrition_plan(profile)

    # ── display in terminal ──────────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            f"[bold green]✅ Plan ready for {profile['name']}![/bold green]",
            style="green",
        )
    )
    console.print()
    try:
        console.print(Markdown(plan_text))
    except Exception:
        console.print(plan_text)

    # ── save to file ─────────────────────────────────────────────────────────
    filepath = save_plan(profile, plan_text)
    console.print(
        f"\n💾 [bold]Plan saved to:[/bold] [underline]{filepath}[/underline]",
        style="bold green",
    )

    return plan_text
